<?php

declare(strict_types=1);

namespace MuchoCore\Deployment;

use RuntimeException;

final class DeploymentDetailsExporter
{
    public static function token(string $jobDir): string
    {
        $path = $jobDir . '/deployment-details-token';

        if (is_file($path)) {
            $token = trim((string)@file_get_contents($path));
            if (preg_match('/^[a-f0-9]{64}$/', $token) === 1) {
                return $token;
            }
        }

        $token = bin2hex(random_bytes(32));
        if (@file_put_contents($path, $token, LOCK_EX) === false) {
            throw new RuntimeException('Cannot create deployment details token.');
        }

        @chmod($path, 0600);
        return $token;
    }

    public static function writeVps(
        string $jobDir,
        array $status,
        string $adminPassword,
        string $sshPassword,
        string $sshKey,
        string $dbName,
        string $dbUser,
        string $dbPassword,
        string $dbRootPassword
    ): string {
        $domain = 'https://' . trim((string)($status['domain'] ?? ''));

        $lines = [
            'MuchoGDPS Deployment Details',
            '',
            'Keep this file private. It contains passwords and hosting credentials.',
            '',
            'GDPS',
            'GDPS Name: ' . trim((string)($status['gdps_name'] ?? 'Mucho GDPS')),
            'Public URL: ' . $domain,
            'Admin URL: ' . $domain . '/admin/',
            'Admin Username: ' . (string)($status['admin_user'] ?? 'admin'),
            'Admin Password: ' . $adminPassword,
            '',
            'Database',
            'Database Host: db',
            'Database Port: 3306',
            'Database Name: ' . $dbName,
            'Database Username: ' . $dbUser,
            'Database Password: ' . $dbPassword,
            'Database Root Password: ' . $dbRootPassword,
            '',
            'VPS / SSH',
            'SSH Host: ' . (string)($status['host'] ?? ''),
            'SSH Port: ' . (string)($status['port'] ?? 22),
            'SSH Username: root',
            'SSH Authentication: ' . ($sshPassword !== '' ? 'Password' : 'Private key'),
        ];

        if ($sshPassword !== '') {
            $lines[] = 'SSH Password: ' . $sshPassword;
        } else {
            $lines[] = 'SSH Private Key:';
            $lines[] = $sshKey;
        }

        $lines = array_merge($lines, [
            '',
            'Clients',
            'Windows: GeometryDash-MuchoGDPS.exe',
            'Android: GeometryDash-MuchoGDPS.apk',
            'Client storage: /opt/mucho-core/storage/clients/',
            '',
            'Generated by MuchoGDPS / MuchoCore',
        ]);

        return self::write($jobDir, implode(PHP_EOL, $lines) . PHP_EOL);
    }

    private static function write(string $jobDir, string $content): string
    {
        $path = $jobDir . '/deployment-details.txt';
        if (@file_put_contents($path, $content, LOCK_EX) === false) {
            throw new RuntimeException('Unable to create deployment details file.');
        }

        @chmod($path, 0600);
        self::token($jobDir);

        return $path;
    }
}
