#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
CONTRACT="$ROOT/tests/client-fixtures/2.0/endpoints.json"

if [[ ! -f "$CONTRACT" ]]; then
    echo "2.0 RELEASE GATE: FAIL"
    echo "Missing real-client fixture: tests/client-fixtures/2.0/endpoints.json"
    echo "Capture it from a real Geometry Dash 2.0 client trace:"
    echo "python3 tools/client/client-trace-summary.py --expected-family 2.0 --input storage/client-trace.ndjson --output tests/client-fixtures/2.0/endpoints.json"
    exit 1
fi

python3 - "$CONTRACT" <<'PY'
import json
import sys
from pathlib import Path

path = Path(sys.argv[1])
data = json.loads(path.read_text(encoding="utf-8"))

if data.get("generated_by") != "tools/client-trace-summary.py":
    raise SystemExit("2.0 RELEASE GATE: FAIL - fixture was not generated by the trace summary tool")

families = set(data.get("trace_client_families", []))
if families != {"2.0"}:
    raise SystemExit(
        f"2.0 RELEASE GATE: FAIL - trace families are {sorted(families)}"
    )

if not data.get("trace_game_versions"):
    raise SystemExit("2.0 RELEASE GATE: FAIL - trace contains no game version metadata")

if not data.get("trace_binary_versions"):
    raise SystemExit("2.0 RELEASE GATE: FAIL - trace contains no binary version metadata")

endpoints = data.get("endpoints", [])
if not endpoints:
    raise SystemExit("2.0 RELEASE GATE: FAIL - fixture contains no endpoints")

ignored_bootstrap = {
    "checkifserveronline",
    "health",
}

seen = {
    str(endpoint.get("path", "")).split("/")[-1].split(".")[0].lower()
    for endpoint in endpoints
    if str(endpoint.get("path", "")).split("/")[-1].split(".")[0].lower()
    not in ignored_bootstrap
}

for endpoint in endpoints:
    name = str(endpoint.get("path", "")).split("/")[-1].split(".")[0].lower()
    if name in ignored_bootstrap:
        continue
    if set(endpoint.get("client_families", [])) != {"2.0"}:
        raise SystemExit(
            "2.0 RELEASE GATE: FAIL - an endpoint contains non-2.0 client metadata"
        )

required = {
    "loginGJAccount",
    "registerGJAccount",
    "getGJLevels20",
    "uploadGJLevel20",
    "downloadGJLevel20",
    "getGJComments20",
    "uploadGJComment20",
    "getGJUserInfo20",
    "getGJScores20",
    "updateGJUserScore20",
}

aliases = {
    "loginGJAccount": {"logingjaccount", "logingjaccount19", "logingjaccount20"},
    "registerGJAccount": {"registergjaccount", "registergjaccount19", "registergjaccount20"},
    "getGJLevels20": {"getgjlevels", "getgjlevels19", "getgjlevels20"},
    "uploadGJLevel20": {"uploadgjlevel", "uploadgjlevel19", "uploadgjlevel20"},
    "downloadGJLevel20": {"downloadgjlevel", "downloadgjlevel19", "downloadgjlevel20"},
    "getGJComments20": {"getgjcomments", "getgjcomments19", "getgjcomments20"},
    "uploadGJComment20": {"uploadgjcomment", "uploadgjcomment19", "uploadgjcomment20"},
    "getGJUserInfo20": {"getgjuserinfo", "getgjuserinfo19", "getgjuserinfo20"},
    "getGJScores20": {"getgjscores", "getgjscores19", "getgjscores20"},
    "updateGJUserScore20": {"updategjuserscore", "updategjuserscore19", "updategjuserscore20"},
}

missing = sorted(
    name for name in required
    if not seen.intersection(aliases[name])
)

if missing:
    raise SystemExit(
        "2.0 RELEASE GATE: FAIL - real-client fixture is missing required "
        f"2.0 endpoint coverage: {', '.join(missing)}"
    )

print(
    f"2.0 RELEASE GATE: PASS - real 2.0 client fixture with "
    f"{len(endpoints)} unique endpoint(s)"
)
PY
