#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
CONTRACT="$ROOT/tests/client-fixtures/1.9/endpoints.json"

if [[ ! -f "$CONTRACT" ]]; then
    echo "1.9 RELEASE GATE: FAIL"
    echo "Missing real-client fixture: tests/client-fixtures/1.9/endpoints.json"
    echo "Capture it from a real Geometry Dash 1.9 client trace:"
    echo "python3 tools/client/client-trace-summary.py --expected-family 1.9 --input storage/client-trace.ndjson --output tests/client-fixtures/1.9/endpoints.json"
    exit 1
fi

python3 - "$CONTRACT" <<'PY'
import json
import sys
from pathlib import Path

path = Path(sys.argv[1])
data = json.loads(path.read_text(encoding="utf-8"))

if data.get("generated_by") != "tools/client-trace-summary.py":
    raise SystemExit("1.9 RELEASE GATE: FAIL - fixture was not generated by the trace summary tool")

families = set(data.get("trace_client_families", []))
if families != {"1.9"}:
    raise SystemExit(
        f"1.9 RELEASE GATE: FAIL - trace families are {sorted(families)}"
    )

if not data.get("trace_game_versions"):
    raise SystemExit("1.9 RELEASE GATE: FAIL - trace contains no game version metadata")

if not data.get("trace_binary_versions"):
    raise SystemExit("1.9 RELEASE GATE: FAIL - trace contains no binary version metadata")

endpoints = data.get("endpoints", [])
if not endpoints:
    raise SystemExit("1.9 RELEASE GATE: FAIL - fixture contains no endpoints")

ignored_bootstrap = {"checkifserveronline", "health"}

seen = {
    str(endpoint.get("path", "")).split("/")[-1].split(".")[0].lower()
    for endpoint in endpoints
    if str(endpoint.get("path", "")).split("/")[-1].split(".")[0].lower()
    not in ignored_bootstrap
}

for endpoint in endpoints:
    name = str(endpoint.get("path", "")).split("/")[-1].split(".")[0].lower()
    if name in ignored_bootstrap:
        continue
    if set(endpoint.get("client_families", [])) != {"1.9"}:
        raise SystemExit(
            "1.9 RELEASE GATE: FAIL - an endpoint contains non-1.9 client metadata"
        )

required = {
    "loginGJAccount",
    "registerGJAccount",
    "getGJLevels",
    "uploadGJLevel",
    "downloadGJLevel",
    "getGJComments",
    "uploadGJComment",
    "getGJUserInfo",
    "getGJScores",
    "updateGJUserScore",
}

aliases = {
    "loginGJAccount": {"logingjaccount", "logingjaccount19"},
    "registerGJAccount": {"registergjaccount", "registergjaccount19"},
    "getGJLevels": {"getgjlevels", "getgjlevels19"},
    "uploadGJLevel": {"uploadgjlevel", "uploadgjlevel19"},
    "downloadGJLevel": {"downloadgjlevel", "downloadgjlevel19"},
    "getGJComments": {"getgjcomments", "getgjcomments19"},
    "uploadGJComment": {"uploadgjcomment", "uploadgjcomment19"},
    "getGJUserInfo": {"getgjuserinfo", "getgjuserinfo19"},
    "getGJScores": {"getgjscores", "getgjscores19"},
    "updateGJUserScore": {"updategjuserscore", "updategjuserscore19"},
}

missing = sorted(
    name for name in required
    if not seen.intersection(aliases[name])
)

if missing:
    raise SystemExit(
        "1.9 RELEASE GATE: FAIL - real-client fixture is missing required "
        f"1.9 endpoint coverage: {', '.join(missing)}"
    )

print(
    f"1.9 RELEASE GATE: PASS - real 1.9 client fixture with "
    f"{len(endpoints)} unique endpoint(s)"
)
PY
