<?php

declare(strict_types=1);

namespace MuchoCore\Database;

use Dotenv\Dotenv;
use PDO;

final class Database
{
    private PDO $pdo;

    public function __construct()
    {
        $projectRoot = dirname(__DIR__, 2);

        // The project .env contains public deployment configuration.
        Dotenv::createImmutable($projectRoot)->safeLoad();

        // Production database credentials are generated at runtime and stored
        // outside the bind-mounted project directory.
        $runtimeEnv = '/var/lib/muchocore/runtime.env';
        if (is_file($runtimeEnv)) {
            Dotenv::createMutable(
                dirname($runtimeEnv),
                basename($runtimeEnv)
            )->safeLoad();
        }

        // Docker/FPM deployments use a root-owned runtime configuration file
        // generated by the container entrypoint. Read it directly so the web
        // worker does not depend on inherited process environment variables.
        $runtimeConfig = [];

        if (is_readable($runtimeEnv)) {
            $runtimeContent = file_get_contents($runtimeEnv);

            if ($runtimeContent !== false && $runtimeContent !== '') {
                try {
                    $runtimeConfig = Dotenv::parse($runtimeContent);
                } catch (\Throwable) {
                    $runtimeConfig = [];
                }
            }
        }

        // On shared hosting, provider-level environment variables can contain
        // generic names such as DB_HOST or DB_USER. Those must never override
        // the database credentials configured by MuchoCore in its own .env.
        $projectConfig = [];

        if (is_readable($projectRoot . '/.env')) {
            $projectContent = file_get_contents($projectRoot . '/.env');

            if ($projectContent !== false && $projectContent !== '') {
                try {
                    $projectConfig = Dotenv::parse($projectContent);
                } catch (\Throwable) {
                    $projectConfig = [];
                }
            }
        }

        $host = (string)(
            $runtimeConfig['DB_HOST']
            ?? $projectConfig['DB_HOST']
            ?? $_ENV['DB_HOST']
            ?? getenv('DB_HOST')
            ?: '127.0.0.1'
        );

        $port = (string)(
            $runtimeConfig['DB_PORT']
            ?? $projectConfig['DB_PORT']
            ?? $_ENV['DB_PORT']
            ?? getenv('DB_PORT')
            ?: '3306'
        );

        $name = (string)(
            $runtimeConfig['DB_NAME']
            ?? $projectConfig['DB_NAME']
            ?? $_ENV['DB_NAME']
            ?? getenv('DB_NAME')
            ?: ''
        );

        $user = (string)(
            $runtimeConfig['DB_USER']
            ?? $projectConfig['DB_USER']
            ?? $_ENV['DB_USER']
            ?? getenv('DB_USER')
            ?: ''
        );

        $pass = (string)(
            $runtimeConfig['DB_PASS']
            ?? $projectConfig['DB_PASS']
            ?? $_ENV['DB_PASS']
            ?? getenv('DB_PASS')
            ?: ''
        );
        $dsn = "mysql:host={$host};port={$port};dbname={$name};charset=utf8mb4";

        $this->pdo = new PDO($dsn, $user, $pass, [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            PDO::ATTR_EMULATE_PREPARES => false,
        ]);
    }

    public function connection(): PDO
    {
        return $this->pdo;
    }
}
