<?php

declare(strict_types=1);

namespace MuchoCore\Core;

use Dotenv\Dotenv;
use Throwable;

final class Environment
{
    /** @var array<string,string|null> */
    private static array $cache = [];

    public static function get(string $key, ?string $default = null): ?string
    {
        if (array_key_exists($key, self::$cache)) {
            return self::$cache[$key];
        }

        $root = dirname(__DIR__, 2);
        $value = null;

        // Runtime secrets/config generated by the Docker entrypoint have the
        // highest priority. This file intentionally contains only runtime
        // values needed by the container, primarily database credentials.
        $runtime = is_file('/.dockerenv')
            ? self::loadFile('/var/lib/muchocore/runtime.env')
            : [];
        if (array_key_exists($key, $runtime) && $runtime[$key] !== '') {
            $value = $runtime[$key];
        }

        // The installation's own .env is the source of truth for
        // deployment-specific MuchoCore settings.
        if ($value === null) {
            $project = self::loadFile($root . '/.env');

            if (is_file($root . '/.env.local')) {
                $local = self::loadFile($root . '/.env.local');
                $project = array_merge($project, $local);
            }

            if (array_key_exists($key, $project) && $project[$key] !== '') {
                $value = $project[$key];
            }
        }

        // Process environment is only the final fallback. Keep project-level
        // configuration authoritative before accepting generic process values.
        if ($value === null) {
            foreach ([
                static fn(string $name): mixed => $_ENV[$name] ?? null,
                static fn(string $name): mixed => $_SERVER[$name] ?? null,
                static fn(string $name): mixed => getenv($name),
            ] as $source) {
                $candidate = $source($key);
                if (is_string($candidate) && $candidate !== '') {
                    $value = $candidate;
                    break;
                }
            }
        }

        return self::$cache[$key] = $value !== null ? $value : $default;
    }

    /** @return array<string,string> */
    private static function loadFile(string $path): array
    {
        if (!is_readable($path)) {
            return [];
        }

        $content = @file_get_contents($path);
        if (!is_string($content) || $content === '') {
            return [];
        }

        try {
            $parsed = Dotenv::parse($content);
        } catch (Throwable) {
            return [];
        }

        $result = [];
        foreach ($parsed as $key => $value) {
            if (is_string($key) && is_string($value)) {
                $result[$key] = $value;
            }
        }

        return $result;
    }
}
