- name: Commit and Push changes
  run: |
    git config --local user.email "errorandrey70@gmail.com"
    git config --local user.name "IZKGMD"
    
    git add .
    git commit -m "chore: update release assets [skip ci]"
    git push origin HEAD:${{ github.event.release.target_commitish }}
